import './globals.css'
import '@/styles/globals.scss'
import React from 'react'
import localFont from 'next/font/local'
import { Lato } from 'next/font/google'
import { getClient } from "@/lib/client";
import GlobalQuery from '@/queries/global'
import { ThemeContextProvider } from '@/context/theme'
import Header from '@/components/generic/header/header'
import Footer from '@/components/generic/footer/footer'
import ContactForm from '@/components/generic/contact_form/contact_form'
import MouseCursor from "@/components/generic/mouse_cursor/mouse_cursor";
import { PageTransition } from '@/components/generic/page_transition/page_transition'
import { motion } from "framer-motion";

const lato = Lato({
  weight: ['100','300','400','700','900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lato',
});
const nothingyoucoulddo = localFont({
  src: [
    {
      path: '../public/fonts/NothingYouCouldDo/NothingYouCouldDo.woff2',
      weight: '400',
      style: 'normal'
    }
  ],
  variable: '--font-nothingyoucoulddo'
});

export const metadata = {
  title: 'Dojo Agency',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const client = getClient();
  const { data } = await client.query({query: GlobalQuery});
  return (
      <html lang="en">
        <head />
        <body className={`${lato.variable} ${nothingyoucoulddo.variable} font-lato`}>
          <main>
            <ThemeContextProvider>
              <MouseCursor />
              <ContactForm data={data.footer} />
              <Header nav={data.header_nav} />
              <PageTransition >
                {children}
              </PageTransition>
              <Footer footer={data.footer} footer_nav={data.footer_nav} />
            </ThemeContextProvider>
          </main>
        </body>
      </html>
  )
}




